num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number:"))

print("The sum of the two numbers is:", num1 + num2)
print("The product of the two numbers is:", num1 * num2)
print("The difference of the two numbers is:", num1 - num2)
print("The quotient of the two numbers is:", num1 / num2)
print("The division of the two numbers is:", num1 // num2)
print("The remainder of the two numbers is:", num1 % num2)
print("The power of the two numbers is:", num1 ** num2)